const fs = require("fs");
const path = require("path");

// Helper to get random value from JSON file
function getRandomFrom(file) {
  const data = JSON.parse(
    fs.readFileSync(path.join(__dirname, "..", "data", file))
  );
  return data[Math.floor(Math.random() * data.length)];
}

// Load fortune data
const quote = getRandomFrom("quotes.json");
const tip = getRandomFrom("cybertips.json");
const challenge = getRandomFrom("challenges.json");

// Timestamp to force a change each run
const timestamp = new Date().toLocaleString("en-IN", {
  timeZone: "Asia/Kolkata",
});

// README content
const content = `
<!-- AUTO-GENERATED BY FORTUNE NINJA 🧙‍♂️ -->

![yin-yang](./img/yinnyang.gif)

## 🔮 Fortune Ninja (Daily Drop)

\`\`\`bash
📜 Quote of the Day:
"${quote}"

🛡️ Cyber Tip:
${tip}

🧠 Challenge of the Day:
${challenge}
\`\`\`

> 🧙‍♂️ Stay sharp, warrior. Return tomorrow for your next fortune.

🕒 Last updated: ${timestamp}
`;

fs.writeFileSync("README.md", content);
