const fs = require("fs");
const path = require("path");

function getRandomFrom(file) {
  try {
    const data = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "data", file)));
    return data[Math.floor(Math.random() * data.length)];
  } catch (error) {
    console.error(`❌ Error reading ${file}:`, error.message);
    return "Oops! Could not load content.";
  }
}

const quote = getRandomFrom("quotes.json");
const tip = getRandomFrom("cybertips.json");
const challenge = getRandomFrom("challenges.json");

const gifBanner = `
<p align="center">
  <img src="./img/yinnyang.gif" width="150" alt="Yin Yang" />
</p>
`;

const content = `
<!-- AUTO-GENERATED BY FORTUNE NINJA 🧙‍♂️ -->
${gifBanner}
## 🔮 Fortune Ninja (Daily Drop)

\`\`\`bash
📜 Quote of the Day:
"${quote}"

🛡️ Cyber Tip:
${tip}

🧠 Challenge of the Day:
${challenge}
\`\`\`

> 🧙 Stay sharp, return tomorrow for your next fortune.
`;
