const fs = require("fs");
const path = require("path");

function getRandomFrom(file) {
  const data = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "data", file)));
  return data[Math.floor(Math.random() * data.length)];
}

const quote = getRandomFrom("quotes.json");
const tip = getRandomFrom("cybertips.json");
const challenge = getRandomFrom("challenges.json");

const content = `
<!-- AUTO-GENERATED BY FORTUNE NINJA 🧙‍♂️ -->
## 🔮 Fortune Ninja (Daily Drop)

\`\`\`bash
📜 Quote of the Day:
"${quote}"

🛡️ Cyber Tip:
${tip}

🧠 Challenge of the Day:
${challenge}
\`\`\`

> 🧙 Stay sharp, BitNinja. Return tomorrow for your next fortune.
`;

fs.writeFileSync("README.md", content);

function getRandomFrom(file) {
  try {
    const data = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "data", file), "utf-8"));
    if (!Array.isArray(data) || data.length === 0) {
      throw new Error(`${file} is empty or not a valid array`);
    }
    return data[Math.floor(Math.random() * data.length)];
  } catch (err) {
    console.error(`❌ Error reading ${file}:`, err.message);
    return "⚠️ Error loading data.";
  }
}
